#!/usr/bin/env python
# coding: utf-8

'''
  Usage: custom-usage [options]

  Options:

    -h, --help                 output this information
    -V, --version              output the version number
'''

import sys
from puppet import puppet

puppet('simple', '0.1.0', plugin=True)


def main(program):
    print('main')


def help(program, value):
    print('abc 123')
    sys.exit(0)
