#!/usr/bin/env python
# coding: utf-8

'''
  Usage: simple-plugin [options]

  Options:

    -h, --help                 output this information
    -V, --version              output the version number
'''

from puppet import puppet

puppet('simple-plugin', '0.1.0')


def main(program):
    print('plugin')
